import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Insurance } from '../models/insurance.model';
import { InsuranceService } from '../services/insurance.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-add-insurance',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './add-insurance.html',
  styleUrl: './add-insurance.css',
})
export class AddInsurance {

  // Model object to bind to the form inputs
  insurance: Insurance = {
    id: 0, // ID is usually auto-generated by the backend (JSON server does this for us if we don't send it, or if we send 0 it might just overwrite it. Best practice is to omit ID for creation, but our interface requires it. We will handle this.)
    name: '',
    policyNumber: '',
    policyType: '',
    premium: 0,
    phone: '',
    email: '',
    dateOfBirth: '',
    nominee: '',
    address: {
      street: '',
      city: '',
      state: '',
      pincode: ''
    }
  };

  constructor(
    private insuranceService: InsuranceService,
    private router: Router
  ) { }

  saveInsurance() {
    console.log('Submitting insurance data:', this.insurance);

    // Create a copy and remove ID so JSON Server generates a new one
    // We cast to unknown first to bypass type checking for the deconstruction
    const { id, ...insuranceData } = this.insurance;

    // We call the service method
    this.insuranceService.addInsurance(insuranceData as unknown as Insurance).subscribe({
      next: (data) => {
        console.log('Insurance added successfully', data);
        // Navigate back to the list page
        this.router.navigate(['/']);
      },
      error: (err) => {
        console.error('Error adding insurance', err);
      }
    });
  }
}
